name: Arm64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            apt update
            apt install wget -y
            mkdir dotnet
            cd dotnet
            wget https://download.visualstudio.microsoft.com/download/pr/f7739964-9e84-4bb7-9435-509458a15f9c/a95ad7f9deb8ce2fd30173dfe86f55ba/dotnet-sdk-9.0.100-rc.1.24452.12-linux-arm64.tar.gz
            tar -xf dotnet-sdk-9.0.100-rc.1.24452.12-linux-arm64.tar.gz
            export DOTNET_ROOT=/home/runner/work/AssetRipper_Arm64/AssetRipper_Arm64/dotnet
            cd ..
            dotnet publish -c Release -r linux-arm64
            ls -R ./Source/0Bins/AssetRipper.GUI.Free/Release/
            date -u > ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/compile_time.txt
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: AssetRipper_${{ matrix.config.name }}
          path: |
            ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/AssetRipper.GUI.Free
            ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/*.so
            ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/compile_time.txt
          if-no-files-found: error
