name: Arm64
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish
        run: dotnet publish -c Release -r linux-arm64
        working-directory: ./Source/AssetRipper.GUI.Free/

      - name: List Files
        shell: bash
        run: ls -R ./Source/0Bins/AssetRipper.GUI.Free/Release/

      - name: List Files
        shell: bash
        run: date -u > ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/compile_time.txt

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: AssetRipper_${{ matrix.config.name }}
          path: |
            ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/AssetRipper.GUI.Free
            ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/*.dll
            ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/*.so
            ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/*.dylib
            ./Source/0Bins/AssetRipper.GUI.Free/Release/linux-arm64/publish/compile_time.txt
          if-no-files-found: error
