name: Arm64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            sudo apt update
            sudo apt install wget -y
            mkdir dotnet
            cd dotnet
            wget https://download.visualstudio.microsoft.com/download/pr/f7739964-9e84-4bb7-9435-509458a15f9c/a95ad7f9deb8ce2fd30173dfe86f55ba/dotnet-sdk-9.0.100-rc.1.24452.12-linux-arm64.tar.gz
            tar -xf dotnet-sdk-9.0.100-rc.1.24452.12-linux-arm64.tar.gz
            export DOTNET_ROOT=$PWD:$PATH
            cd ..
            dotnet --list-sdks
            pwd
